#!/bin/sh

## declare an array variable
declare -a arr=("email1"
                "email2"
                "emailN")

declare -a parr=("pass1"
                 "pass2"
                 "passN")

x=1
## now loop through the above array
for i in "${arr[@]}"
do
    x=$[$x +1]
    uname="ouecon"$(printf "%03d " $x)
    touch information.txt
    echo "The following email has been auto-generated by Professor Ransom and includes your login credentials to the OSCER computing cluster for Spring 2018." >> information.txt
    echo "" >> information.txt
    echo "" >> information.txt
    echo "Username: $uname" >> information.txt
    echo "Temporary password: ${parr[$[$x-2]]}" >> information.txt
    mutt -s 'OSCER login credentials' $i < information.txt
    rm -f information.txt
done
